### ISSUE TITLE
Doesn't seem to attempt healthcheck after initial start.

### ISSUE THREAD

**Issue by niklasravnsborg** [zekizeki/healthcheck#1]
Hey there! I tried to install it with docker-compose.yml. I `docker-compose up` your container, than bring the server in an unhealthy state. It doesn't get reported to my Slack and it doesn't get logged. It seems like the interval doesn't work properly. When my service is unhealthy and I then start your checks the notification is sent properly.

```
  app-healthcheck:
    image: zekizeki/healthcheck:latest
    environment:
      - SERVER=microservice.example.com
      - USE_HTTPS=true
      - INTERVAL=60000
      - NOTIFY_AFTER=1
      - CONTEXT_PATH=/
      - NOTIFICATION_USER=Healthcheck
      - NOTIFICATION_URL=https://hooks.slack.com/services/.........
```
